name: Auto Create Branch from Issue

on:
  issues:
    types: [opened]

jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create Branch
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          # Clean up the issue title to create a branch name
          BRANCH_NAME="issue-${ISSUE_NUMBER}-$(echo ${ISSUE_TITLE} | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9]/-/g' | cut -c1-50)"
          
          # Create a new branch
          git checkout -b $BRANCH_NAME

          # Push the new branch to GitHub
          git push origin $BRANCH_NAME

      - name: Link Branch to the Issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
            const branchName = `issue-${issueNumber}-${context.payload.issue.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').substring(0, 50)}`;

            const updatedBody = `
              ${context.payload.issue.body}

              ### Linked Branch:
              \`${branchName}\`
            `;

            // Update the issue body to include the new branch reference
            github.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: updatedBody
            });
